spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

springdoc:
  api-docs:
    path: /api-docs  # (선택) 기본은 /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html  # (선택) 기본은 /swagger-ui/index.html